defaults: &defaults
  foursquare_app_id: <%= ENV['FOURSQUARE_APP_ID'] %>
  foursquare_app_secret: <%= ENV['FOURSQUARE_APP_SECRET'] %>
  foursquare_app_push_secret: <%= ENV['FOURSQUARE_PUSH_SECRET'] %>

  twilio_app_sid: <%= ENV['TWILIO_APP_SID'] %>
  twilio_secret: <%= ENV['TWILIO_APP_SECRET'] %>
  twilio_from_number: <%= ENV['TWILIO_SMS_PHONE_NUMBER'] %>

  heroku_app_name: <%= ENV['HEROKU_APP_NAME'] %>
  heroku_app_key: <%= ENV['HEROKU_API_KEY'] %>

  fog_directory: <%= ENV['FOG_DIRECTORY'] %>

  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults